### ISSUE TITLE
space between log lines too big

### ISSUE THREAD

**Issue by giangm9** [hans-lizihan/bull-master#2]
As the title say, spacing is too big
![Screenshot from 2020-05-21 13-03-03](https://user-images.githubusercontent.com/10234339/82528662-7bd75a80-9b63-11ea-8609-3a946a52a719.png)

**Comment by hans-lizihan** [comment]
how large you deem appropriate @giangm9

**Comment by giangm9** [comment]
`<pre>`'s `magrin` should be `0px`, and `padding` should be `1-3px`,  sorry i cant edit in the browser to show you the result

**Comment by hans-lizihan** [comment]
this should be streamed in next release. the code is ready @giangm9
