### ISSUE TITLE
Provide a way to asynchronously set queues

### ISSUE THREAD

**Issue by jcarrillo7** [hans-lizihan/bull-master#27]
bull-board allows for setting the queues asynchronously. It would be nice to continue to have some way of doing this as it helps with integration with frameworks like NestJS.

Similar to how its described here: https://medium.com/@gdr2409/bull-queues-in-nestjs-306c51cb0ec2

**Comment by hans-lizihan** [comment]
actually you could do this

```
const bullMaseterApp = bullMaster({
  queues: [queue1, queue2]
})

// in other files
bullMasterApp.local.bullMasterQueues.asyncQueue1 = asyncQueue1
```

i could also provide a better API like this in the next version

```
bullMasterApp.getQueues() // get the current queues
bullMasterApp.setQueues([q1, q2]) // set queues in the server
```

**Comment by jcarrillo7** [comment]
I found a way around my issue using some NestJs constructs but the setQueues, replaceQueues features would make it simpler and support more dynamic queues. Thanks!

**Comment by hans-lizihan** [comment]
latest code is committed and readme updated
