### ISSUE TITLE
Low version Redis will cause the dashboard crash 

### ISSUE THREAD

**Issue by jakechan2012** [hans-lizihan/bull-master#72]
### Below is the response of api `/api/redis-stats`

- Redis version lower then 5.0

```json
{
  "redisVersion": "3.0.6",
  "usedMemory": "66331368",
  "memFragmentationRatio": "1.03",
  "connectedClients": "660",
  "blockedClients": "2"
}
```

- Redis version upper then 5.0

```json
{
  "redisVersion": "5.0.5",
  "usedMemory": "1406312",
  "memFragmentationRatio": "2.89",
  "connectedClients": "7",
  "blockedClients": "2",
  "totalSystemMemory": "2087837696"
}
```

the lost property `totalSystemMemory` will trigger the dashboard crash，

![image](https://user-images.githubusercontent.com/4206535/89614381-e2dcf380-d8b6-11ea-970c-d7e38b5b1b61.png)

bull 3 require redis version > `2.8.18`, 

so this amazing UI could compatible with lower versions?

many thanks!

**Comment by hans-lizihan** [comment]
@jakechan2012 sorry for the delay. the it should've been fixed in 1.0.5
